### ISSUE TITLE
Matplotlib 3.1.1 issue with heatmap function

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#629]
There is a bug/issue with the current matplotlib function. It seems that `plt.matshow` cuts off the current outer cells by half. E.g., before the heatmap function produced heatmaps like the following:

![Screen Shot 2019-11-19 at 10 29 54 PM](https://user-images.githubusercontent.com/5618407/69210259-c24ded00-0b1f-11ea-87f1-29f3aedacf02.png)

It works fine with matplotlib 3.1.0, but with 3.1.1 it looks like this:

![Screen Shot 2019-11-19 at 10 56 36 PM](https://user-images.githubusercontent.com/5618407/69210291-d98cda80-0b1f-11ea-8c1c-390c3ba726c7.png)

**Comment by rasbt** [comment]
Seems to be a matplotlib 3.1.1. bug and will be fixed in the next release.

See https://github.com/matplotlib/matplotlib/issues/15733

**Comment by Semiu** [comment]
Please, maybe this current experience of mine with heatmap is related to this thread.
`ImportError: cannot import name 'heatmap' from 'mlxtend.plotting' (/usr/local/lib/python3.7/dist-packages/mlxtend/plotting/__init__.py)`

I had imported and used `scatterplotmatrix` earlier. So, the problem is not with `mlxtend.plotting`.

Thank you.

**Comment by rasbt** [comment]
Can you print the version number of mlxtend? 

>>> import mlxtend
>>> from mlxtend.plotting import heatmap
>>> print(mlxtend.__version__)

**Comment by Semiu** [comment]
![mlxtend](https://user-images.githubusercontent.com/7491305/204166986-69b9559c-8c37-4906-a247-e370c5dbc8ad.png)

I needed to comment out the second line because it was throwing the same error earlier mentioned. Thank you for all you do for the community, Rasbt.

**Comment by rasbt** [comment]
Looks like we found the culprit :). Mlxtend's current version is 0.21 (http://rasbt.github.io/mlxtend/CHANGELOG/), and the `heatmap` function as added in 0.17.0. 

I recommend running


    pip install mlxtend --upgrade

or 

    conda update mlxtend -c conda-forge

**Comment by Semiu** [comment]
![Screenshot_20221127_062608](https://user-images.githubusercontent.com/7491305/204168230-8a0a2320-7a08-40c5-b712-705ae53795e9.png)

Thank you!
