### ISSUE TITLE
Error thrown when trying to import StackingClassifier

### ISSUE THREAD

**Issue by datatales2017** [rasbt/mlxtend#252]
When I run the below command in Python
"from mlxtend.classifier import StackingClassifier" 
I get the error
'ImportError: No module named 'sklearn.exceptions''

I have sucessfully installed mlxtend using pip install mlxtend before this.

**Comment by rasbt** [comment]
Thanks for the note!
Curious, have you installed scikit-learn on your machine?

**Comment by datatales2017** [comment]
Yes.

**Comment by rasbt** [comment]
And if you execute

    import sklearn.exceptions

in your python interpreter, does that work?

**Comment by datatales2017** [comment]
I dont see an option like 'exceptions' when I type in 'sklearn.' 
I can see only ensembles and externals under letter 'e'

**Comment by rasbt** [comment]
It should be there in the top-level module directory, not as a submodule but as a package (or how it's called) -- by that, I mean it's not a directory sklearn/exceptions but sklearn/exceptions.py

E.g., see

    https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/exceptions.py

**Comment by datatales2017** [comment]
I really did not get this.I am sorry about it. What exactly should I be doing??

**Comment by rasbt** [comment]
Hm, could be that it doesn't work in 0.17.1 -- I just see that the oldest version that is tested in the unit/CI tests of mlxtend is 0.18. Would it be possible for you to update to 0.18, 0.18.1, or 0.19.0? This would solve the problem I guess

**Comment by datatales2017** [comment]
upgraded sklearn version to 0.19.
Now, it works fine.No error.
Thank you.

P.S: waiting for your new book. I pre-booked it on amazon. :)

**Comment by rasbt** [comment]
Nice, I am glad that upgrading scikit-learn solved that issue :). (PS: thanks for the interest in my book! I think the layout team already finished their part, and I hope it will be out in the next couple of days!)

**Comment by ak5127** [comment]
I want to use the Stacking classifier in python. I using the below code.
"from sklearn.ensemble import StackingClassifier"
**_It shows error as:_**
"ImportError                               Traceback (most recent call last)
<ipython-input-3-4a097712a99d> in <module>
----> 1 from sklearn.ensemble import StackingClassifier

ImportError: cannot import name 'StackingClassifier' from 'sklearn.ensemble' (C:\Users\Hassan\Anaconda3\lib\site-packages\sklearn\ensemble\__init__.py)"
kindly tell me solution anyone how can I use the Stacking ensemble learning classifier
Thanks in advance...

**Comment by rasbt** [comment]
The stacking classifiers in mlxtend are imported via 

```python
from mlxtend.ensemble import StackingClassifier
```

or

```
from mlxtend.ensemble import StackingCVClassifier
```

for the recommended version of stacking. Scikit-learn also implements a stacking classifier now, which is what you were referring to? I think the reason it does not work in your case is that you may have an older version of sklearn installed -- I think they just added it very recently.

**Comment by AbdeslamRehaimi** [comment]
> The stacking classifiers in mlxtend are imported via
> 
> ```python
> from mlxtend.ensemble import StackingClassifier
> ```
> 
> or
> 
> ```python
> from mlxtend.ensemble import StackingCVClassifier
> ```
> 
> for the recommended version of stacking. Scikit-learn also implements a stacking classifier now, which is what you were referring to? I think the reason it does not work in your case is that you may have an older version of sklearn installed -- I think they just added it very recently.

tried this but it seems not working, i got this error as No module named 'mlxtend.ensemble' 
"ModuleNotFoundError: No module named 'mlxtend.ensemble'"
